input_dir: taaalcr_data/input
output_dir: taaalcr_data/output
reliability_fraction: 0.2
automate_powers: true
just_c2_powers: false
exclude_participants:
coders:
- '1'
- '2'
- '3'
tiers:
  site:
    values:
    - AC
    - BU
    - TU
    partition: true
  test:
    values:
    - Pre
    - Post
    - Maint
  study_id:
    values: (AC|BU|TU)\d+
  communication:
    values: Dialogue